config/routes.rb
Rails.application.routes.draw do
  get 'manual/manual_myclinic'
  
  root 'appointments#index'  
  resources :customers
  resources :professionals
  resources :appointments
  get 'report/index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord

  belongs_to :customer
  belongs_to :professional

  validates :date, :hour, :customer_id, :professional_id, :category, presence: true

end

app/models/customer.rb
class Customer < ApplicationRecord

  has_many :appointment, dependent: :destroy

  validates :name, :email, :cell_phone, :cpf, :age, presence: true 
end

app/models/professional.rb
class Professional < ApplicationRecord

  has_many :appointment, dependent: :destroy

  validates :name, :email, :cell_phone, :cpf, :specialty, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

  before_action :set_appointment, only: %i[show edit update destroy]

  def index

    if(params[:cpf].to_s != "")

      customer_find = Customer.where(cpf: params[:cpf])
      @appointments = Appointment.where(customer_id: customer_find).page(params[:page]).per(5)
      
    else
      
      @appointments = Appointment.order(:id).page(params[:page]).per(10)
    
    end

    if !params[:cpf]

      @appointments = Appointment.order(:id).page(params[:page]).per(10)
    
    end 
    
    @total_appointments = Appointment.all
    @appointments_returns = Appointment.where("category == '2'")


  end

  def show

  end

  def new

    @appointment = Appointment.new

  end

  def edit

  end

  def create

    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html {redirect_to appointment_url(@appointment), notice: "Consulta criada."}
      else
        format.html {render :new, status: :unprocessable_entity}
      end
    end

  end

  def update

    respond_to do |format|

      if @appointment.update(appointment_params)
        format.html { redirect_to appointment_url(@appointment), notice: "Consulta atualizada."}      
      else
        format.html { render :edit, status: :unprocessable_entity}
      end
      
    end

  end

  def destroy

    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Consulta apagada com sucesso.' }
    end

  end

private

  def set_appointment

    @appointment = Appointment.find(params[:id])

  end

  def appointment_params

    params.require(:appointment).permit(:date, :hour, :customer_id, :professional_id, :category)

  end  

end

app/controllers/customers_controller.rb
require 'send_sms'

class CustomersController < ApplicationController

  before_action :set_customer, only: %i[show edit update destroy]

  def index

    if(params[:cpf].to_s != "")

      customer_find = Customer.where(cpf: params[:cpf])
      @customers = Customer.where(id: customer_find)
      
    else
      
      @customers = Customer.order(:id).page(params[:page]).per(10)
    
    end

    if !params[:cpf]

      @customers = Customer.order(:id).page(params[:page]).per(10)
    
    end
    
    @total_customers = Customer.all
    
    @customers_maiores_18 = Customer.where("age > '18'")

  end

  def show

  end

  def new

    @customer = Customer.new

  end

  def edit

  end

  def create

    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        # SendSms.new("Parabéns #{@customer.name}, você foi cadastrado no MyClinic!", @customer.cell_phone).call
        ContactMailer.contact_email(@customer).deliver_now
        format.html {redirect_to customer_url(@customer), notice: "Cliente criado."}
      else
        format.html {render :new, status: :unprocessable_entity}
      end
    end

  end

  def update

    respond_to do |format|

      if @customer.update(customer_params)
        format.html { redirect_to customer_url(@customer), notice: "Cliente atualizado."}      
      else
        format.html { render :edit, status: :unprocessable_entity}
      end
      
    end

  end

  def destroy
  
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Cliente apagado com sucesso.' }
    end

  end

private

  def set_customer

    @customer = Customer.find(params[:id])

  end

  def customer_params

    params.require(:customer).permit(:name, :email, :cell_phone, :cpf, :age)

  end

end

app/controllers/manual_controller.rb
class ManualController < ApplicationController
  def manual_myclinic
  end
end

app/controllers/professionals_controller.rb
class ProfessionalsController < ApplicationController

  before_action :set_professional, only: %i[show edit update destroy]

  def index

    if(params[:cpf].to_s != "")

      professional_find = Professional.where(cpf: params[:cpf])
      @professionals = Professional.where(id: professional_find).page(params[:page]).per(5)
      
    else
      
      @professionals = Professional.order(:id).page(params[:page]).per(10)
    
    end

    if !params[:cpf]

      @professionals = Professional.order(:id).page(params[:page]).per(10)
    
    end
    
    @total_professionals = Professional.all
    @professionals_clinicos = Professional.where("specialty == '1'")

  end

  def show
  end

  def new

    @professional = Professional.new

  end

  def edit
  end

  def create

    @professional = Professional.new(professional_params)

    respond_to do |format|
      if @professional.save
        format.html { redirect_to professional_url(@professional), notice: "Profissional criado." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  
  end

  def update

    respond_to do |format|
      if @professional.update(professional_params)
        format.html { redirect_to professional_url(@professional), notice: "Profissional atualizado."}
      else
        format.html { render :edit, status: :unprocessable_entity}
      end
    end
    
  end

  def destroy

    @professional.destroy
    respond_to do |format|
      format.html { redirect_to professionals_url, notice: 'Profissional apagado com sucesso.' }
    end

  end


private

  def set_professional

    @professional = Professional.find(params[:id])

  end

  def professional_params

    params.require(:professional).permit(:name, :email, :cell_phone, :cpf, :specialty)

  end
  
end

app/controllers/report_controller.rb
require 'charts'

class ReportController < ApplicationController
  def index

    @total_customers = Customer.all
    @customers_18 = Customer.where("age > '18'")

    @total_professionals = Professional.all
    @clinic_professionals = Professional.where("specialty == '1'")

    @total_appointments = Appointment.all
    @appointments_returns = Appointment.where("category == '2'")

    Charts.new(@total_appointments.size, @appointments_returns.size, 0, 0).gerar_grafico_consultas

    Charts.new(0, 0, @total_customers.size, @customers_18.size).gerar_grafico_clientes

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/manual_helper.rb
module ManualHelper
end

app/helpers/report_helper.rb
module ReportHelper
end

app/views/appointments/_appointment.html.erb
<div id="<%= dom_id appointment %>">

  <p class="card-text">
    <strong class="campo">Data:</strong>
    <%= appointment.date %>
  </p>
   
  <p class="card-text">
    <strong class="campo">Hora:</strong>
    <%= appointment.hour %>
  </p>  

  <p class="card-text">
    <strong class="campo">Cliente:</strong>
    <%= appointment.customer_id %>
  </p>

  <p class="card-text">
    <strong class="campo">Profissional:</strong>
    <%= appointment.professional_id %>
  </p>

  <p class="card-text">
    <strong class="campo">Categoria:</strong>
    <%= appointment.category %>
  </p>

</div>

  </div> <!-- final card -->
  </div> <!-- final card -->

app/views/appointments/_form.html.erb
<%= form_with(model: appointment, multipart: true) do |form|  %>
  <% if appointment.errors.any? %>
    <div style="color: red">
      <ul class="alert alert-danger" role="alert">
        <% appointment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="mb-3">
    <%= form.label :date, class: "form-label campo" %>
    <%= form.text_field :date, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :hour, class: "form-label campo" %>
    <%= form.text_field :hour, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :customer_id, class: "form-label campo" %>
    <%= form.number_field :customer_id, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :professional_id, class: "form-label campo" %>
    <%= form.number_field :professional_id, class: "form-control" %>
  </div>  

  <div class="mb-3">
    <%= form.label :category, class: "form-label campo" %>
    <%= form.text_field :category, class: "form-control" %>
  </div>

  <div class="mb-3 centraliza">
    <%= form.submit "Salvar", class: "btn btn-sm btn-primary cor-customizada" %>
  <div/>
<% end %>

app/views/appointments/edit.html.erb
<h3 class="titulo">Editar consulta</h3>

<%= render "form", appointment: @appointment %>

<br>

<div>
  
</div>

app/views/appointments/index.html.erb
<p style="color: green"><%= notice %></p>

<h3 class="titulo">Consultas</h3>
<div class="album py-1 bg-light">   
  <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 g-3">
    <div class="col">
      <div class="card shadow-sm ">
        <div class="card-header text-center my-card">
          <h4>Total de Consultas<h4>
        </div>
        <div class="card-body text-center my-card">
          <h2><%= @total_appointments.size %></h2>    
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card shadow-sm ">
        <div class="card-header text-center my-card">
          <h4>Total de Retornos<h4>
        </div>
        <div class="card-body text-center my-card">
          <h2> <%= @appointments_returns.size %> </h2>    
        </div>
      </div>
    </div>
  </div>    
</div>

<div class="mb-3 form-pesquisa">
  <%= form_tag( appointments_path, :method => :get, html: {class: "form-inline"}) do %>
    <div class="row g-3 align-items-center">
      <div class="col-auto">
        <%= text_field_tag 'cpf', nil, class: "form-control col-md-6", pattern: "[0-9]{11}", placeholder: "11 dígitos apenas" %>      
      </div>
      <div class="col-auto">
        <%= submit_tag "Pesquisar Cpf", :name => nil, class: "btn btn-primary cor-customizada" %>  
      </div>
      <div class="col-auto">
        <%= link_to t('links.new'), new_appointment_path, class: "btn btn-primary cor-customizada" %>
      </div>  
    </div>
  <% end %>
</div>
<div class="table-responsive">
  <table class="table table-hover table-sm">
    <thead>
      <tr>
        <th scope="col"><%= t'.date' %></th>             
        <th scope="col">Hora</th>
        <th scope="col"><%= t'.customer_id' %></th>
        <th scope="col">Profissional</th> 
        <th scope="col"><%= t'.category' %></th>              
        <th scope="col">Detalhes</th>
      </tr>      
    </thead>      
    <tbody>
      <% @appointments.each do |appointment| %>  
      <tr>
        <td><%= appointment.date %></td>
        <td><%= appointment.hour %></td>
        <td><%= appointment.customer_id %></td>
        <td><%= appointment.professional_id %></td>                
        <td><%= appointment.category %></td>
        <td><%= link_to t('links.show'), appointment, class: "btn btn-sm btn-primary cor-customizada" %></td>
      </tr>
      <% end %>            
    </tbody>
  </table>
  <% if @appointments.size > 1%>
    <div class="centraliza">
      <%= paginate @appointments %>
    </div>   
  <%end%> 
</div>  
      

app/views/appointments/new.html.erb
<h3 class="titulo">Nova consulta</h3>

<%= render "form", appointment: @appointment %>
<br/>
<div>
  
</div>

app/views/appointments/show.html.erb
<p style="color: green"><%= notice %></p>
<h3 class="titulo">Detalhes da consulta</h3>
<div class="card mb-3" > <!-- fechado em _appointment.html.erb -->
  <div class="row g-0"> <!-- fechado em _appointment.html.erb -->
    <div class="col-md-6">
      <div class="card-body">
        <%= render @appointment %>
      </div>
    </div>

    <div class="centraliza">
      <%= link_to t('links.edit'), edit_appointment_path(@appointment), class: "btn btn-sm btn-primary cor-customizada my-link" %>
      <%= link_to 'Imprimir', appointment_path(format: :pdf), target: "_blank",class: "btn btn-sm btn-primary cor-customizada my-link" %>
      <%= button_to "Apagar", appointment_path(@appointment), class: "btn btn-sm btn-primary cor-customizada my-link", form: { data: { turbo_confirm: "Esta ação não pode ser desfeita, deseja continuar?" }}, method: :delete %>
    </div>

app/views/customers/_customer.html.erb
<div id="<%= dom_id customer %>">

  <p class="card-text">
    <strong class="campo">Nome:</strong>
    <%= customer.name %>
  </p>
   
  <p class="card-text">
    <strong class="campo">Email:</strong>
    <%= customer.email %>
  </p>  

  <p class="card-text">
    <strong class="campo">Celular:</strong>
    <%= customer.cell_phone %>
  </p>

  <p class="card-text">
    <strong class="campo">CPF:</strong>
    <%= customer.cpf %>
  </p>

  <p class="card-text">
    <strong class="campo">Idade:</strong>
    <%= customer.age %>
  </p>

</div>

  </div> <!-- final card -->
  </div> <!-- final card -->

app/views/customers/_form.html.erb
<%= form_with(model: customer, multipart: true) do |form|  %>
  <% if customer.errors.any? %>
    <div style="color: red">
      <ul class="alert alert-danger" role="alert">
        <% customer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="mb-3">
    <%= form.label :name, class: "form-label campo" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :email, class: "form-label campo" %>
    <%= form.text_field :email, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :cell_phone, class: "form-label campo" %>
    <%= form.number_field :cell_phone, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :cpf, class: "form-label campo" %>
    <%= form.number_field :cpf, class: "form-control" %>
  </div>  

  <div class="mb-3">
    <%= form.label :age, class: "form-label campo" %>
    <%= form.text_field :age, class: "form-control" %>
  </div>

  <div class="mb-3 centraliza">
    <%= form.submit "Salvar", class: "btn btn-sm btn-primary cor-customizada" %>
  <div/>
<% end %>

app/views/customers/edit.html.erb
<h3 class="titulo">Editar cliente</h3>

<%= render "form", customer: @customer %>

<br>

<div>
  
</div>

app/views/customers/index.html.erb
<p style="color: green"><%= notice %></p>

<h3 class="titulo">Clientes</h3>
<div class="album py-1 bg-light">   
  <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 g-3">
    <div class="col">
      <div class="card shadow-sm ">
        <div class="card-header text-center my-card">
          <h4>Total de Clientes<h4>
        </div>
        <div class="card-body text-center my-card">
          <h2><%= @total_customers.size %></h2>    
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card shadow-sm ">
        <div class="card-header text-center my-card">
          <h4>Clientes maiores de 18 anos<h4>
        </div>
        <div class="card-body text-center my-card">
          <h2> <%= @customers_maiores_18.size %> </h2>    
        </div>
      </div>
    </div>
  </div>    
</div>

<div class="mb-3 form-pesquisa">
  <%= form_tag( customers_path, :method => :get, html: {class: "form-inline"}) do %>
    <div class="row g-3 align-items-center">
      <div class="col-auto">
        <%= text_field_tag 'cpf', nil, class: "form-control col-md-6", pattern: "[0-9]{11}", placeholder: "11 dígitos apenas" %>      
      </div>
      <div class="col-auto">
        <%= submit_tag "Pesquisar Cpf", :name => nil, class: "btn btn-primary cor-customizada" %>  
      </div>
      <div class="col-auto">
        <%= link_to t('links.new'), new_customer_path, class: "btn btn-primary cor-customizada" %>
      </div>  
    </div>
  <% end %>
</div>
<div class="table-responsive">
  <table class="table table-hover table-sm">
    <thead>
      <tr>
        <th scope="col"><%= t'.name' %></th>             
        <th scope="col">Email</th>
        <th scope="col"><%= t'.cell_phone' %></th>
        <th scope="col">Cpf</th> 
        <th scope="col"><%= t'.age' %></th>              
        <th scope="col">Detalhes</th>
      </tr>      
    </thead>      
    <tbody>
      <% @customers.each do |customer| %>  
      <tr>
        <td><%= customer.name %></td>
        <td><%= customer.email %></td>
        <td><%= customer.cell_phone %></td>
        <td><%= customer.cpf %></td>                
        <td><%= customer.age %></td>
        <td><%= link_to t('links.show'), customer, class: "btn btn-sm btn-primary cor-customizada" %></td>
      </tr>
      <% end %>            
    </tbody>
  </table>
  <% if @customers.size > 1%>
    <div class="centraliza">
      <%= paginate @customers %>
    </div>   
  <%end%> 
</div>  
      

app/views/customers/new.html.erb
<h3 class="titulo">Novo cliente</h3>

<%= render "form", customer: @customer %>
<br/>
<div>
  
</div>

app/views/customers/show.html.erb
<p style="color: green"><%= notice %></p>
<h3 class="titulo">Detalhes do cliente</h3>
<div class="card mb-3" > <!-- fechado em _customer.html.erb -->
  <div class="row g-0"> <!-- fechado em _customer.html.erb -->
    <div class="col-md-6">
      <div class="card-body">
        <%= render @customer %>
      </div>
    </div>

    <div class="centraliza">
      <%= link_to t('links.edit'), edit_customer_path(@customer), class: "btn btn-sm btn-primary cor-customizada my-link" %>
      <%= button_to "Apagar", customer_path(@customer), class: "btn btn-sm btn-primary cor-customizada", form: { data: { turbo_confirm: "Esta ação não pode ser desfeita, deseja continuar?" }}, method: :delete %>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myclinic</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="#712cf9">
   
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= stylesheet_link_tag "dashboard", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "estilos-dashboard-adicionais", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "my-styles", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/professionals/_form.html.erb
<%= form_with(model: professional, multipart: true) do |form|  %>
  <% if professional.errors.any? %>
    <div style="color: red">
      <ul class="alert alert-danger" role="alert">
        <% professional.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="mb-3">
    <%= form.label :name, class: "form-label campo" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :email, class: "form-label campo" %>
    <%= form.text_field :email, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :cell_phone, class: "form-label campo" %>
    <%= form.number_field :cell_phone, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :cpf, class: "form-label campo" %>
    <%= form.number_field :cpf, class: "form-control" %>
  </div>  

  <div class="mb-3">
    <%= form.label :specialty, class: "form-label campo" %>
    <%= form.text_field :specialty, class: "form-control" %>
  </div>

  <div class="mb-3 centraliza">
    <%= form.submit "Salvar", class: "btn btn-sm btn-primary cor-customizada" %>
  <div/>
<% end %>

app/views/professionals/_professional.html.erb
<div id="<%= dom_id professional %>">

  <p class="card-text">
    <strong class="campo">Nome:</strong>
    <%= professional.name %>
  </p>
   
  <p class="card-text">
    <strong class="campo">Email:</strong>
    <%= professional.email %>
  </p>  

  <p class="card-text">
    <strong class="campo">Celular:</strong>
    <%= professional.cell_phone %>
  </p>

  <p class="card-text">
    <strong class="campo">CPF:</strong>
    <%= professional.cpf %>
  </p>

  <p class="card-text">
    <strong class="campo">Especialidade:</strong>
    <%= professional.specialty %>
  </p>

</div>

  </div> <!-- final card -->
  </div> <!-- final card -->

app/views/professionals/edit.html.erb
<h3 class="titulo">Editar profissional</h3>

<%= render "form", professional: @professional %>

<br>

<div>
  
</div>

app/views/professionals/index.html.erb
<p style="color: green"><%= notice %></p>

<h3 class="titulo">Profissionais</h3>
<div class="album py-1 bg-light">   
  <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 g-3">
    <div class="col">
      <div class="card shadow-sm ">
        <div class="card-header text-center my-card">
          <h4>Total de Profissionais<h4>
        </div>
        <div class="card-body text-center my-card">
          <h2><%= @total_professionals.size %></h2>    
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card shadow-sm ">
        <div class="card-header text-center my-card">
          <h4>Clínicos<h4>
        </div>
        <div class="card-body text-center my-card">
          <h2> <%= @professionals_clinicos.size %> </h2>    
        </div>
      </div>
    </div>
  </div>    
</div>

<div class="mb-3 form-pesquisa">
  <%= form_tag( professionals_path, :method => :get, html: {class: "form-inline"}) do %>
    <div class="row g-3 align-items-center">
      <div class="col-auto">
        <%= text_field_tag 'cpf', nil, class: "form-control col-md-6", pattern: "[0-9]{11}", placeholder: "11 dígitos apenas" %>      
      </div>
      <div class="col-auto">
        <%= submit_tag "Pesquisar Cpf", :name => nil, class: "btn btn-primary cor-customizada" %>  
      </div>
      <div class="col-auto">
        <%= link_to t('links.new'), new_professional_path, class: "btn btn-primary cor-customizada" %>
      </div>  
    </div>
  <% end %>
</div>
<div class="table-responsive">
  <table class="table table-hover table-sm">
    <thead>
      <tr>
        <th scope="col"><%= t'.name' %></th>             
        <th scope="col">Email</th>
        <th scope="col"><%= t'.cell_phone' %></th>
        <th scope="col">Cpf</th> 
        <th scope="col"><%= t'.specialty' %></th>              
        <th scope="col">Detalhes</th>
      </tr>      
    </thead>      
    <tbody>
      <% @professionals.each do |professional| %>  
      <tr>
        <td><%= professional.name %></td>
        <td><%= professional.email %></td>
        <td><%= professional.cell_phone %></td>
        <td><%= professional.cpf %></td>                
        <td><%= professional.specialty %></td>
        <td><%= link_to t('links.show'), professional, class: "btn btn-sm btn-primary cor-customizada" %></td>
      </tr>
      <% end %>            
    </tbody>
  </table>
  <% if @professionals.size > 1%>
    <div class="centraliza">
      <%= paginate @professionals %>
    </div>   
  <%end%> 
</div>  
      

app/views/professionals/new.html.erb
<h3 class="titulo">Novo profissional</h3>

<%= render "form", professional: @professional %>
<br/>
<div>
  
</div>

app/views/professionals/show.html.erb
<p style="color: green"><%= notice %></p>
<h3 class="titulo">Detalhes do profissional</h3>
<div class="card mb-3" > <!-- fechado em _professional.html.erb -->
  <div class="row g-0"> <!-- fechado em _professional.html.erb -->
    <div class="col-md-6">
      <div class="card-body">
        <%= render @professional %>
      </div>
    </div>

    <div class="centraliza">
      <%= link_to t('links.edit'), edit_professional_path(@professional), class: "btn btn-sm btn-primary cor-customizada my-link" %>
      <%= button_to "Apagar", professional_path(@professional), class: "btn btn-sm btn-primary cor-customizada", form: { data: { turbo_confirm: "Esta ação não pode ser desfeita, deseja continuar?" }}, method: :delete %>
    </div>

app/views/shared/_navbar.html.erb
<header class="navbar navbar-light sticky-top bg-light flex-md-nowrap p-0 shadow">
  <%= link_to "MyClinic", root_path, class: "navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6 navbar-customizada" %>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <input class="form-control form-control-dark w-100 rounded-0 border-0" type="text" readonly="readonly" aria-label="Search">
  <div class="navbar-nav">
    <div class="nav-item text-nowrap">
      <a class="nav-link px-3" href="#">Sair</a>
    </div>
  </div>
</header>

<div class="container-fluid">
  <div class="row"> <!-- abaixo em nav, foi removido bg-light e inserido, cor-sidebar -->
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block cor-sidebar sidebar collapse">
      <div class="position-sticky pt-3">
        <ul class="nav flex-column ">
          <li class="nav-item">
            <%= link_to '<span data-feather="file" class="align-text-bottom"></span><i class="bi bi-person"></i>Clientes'.html_safe, customers_path, class: "nav-link link-mysidebar" %>  
          </li>
          <li class="nav-item">
            <%= link_to '<span data-feather="file" class="align-text-bottom"></span><i class="bi bi-activity"></i>Consultas'.html_safe, appointments_path, class: "nav-link link-mysidebar" %>
          </li>  
          <li class="nav-item">
            <%= link_to '<span data-feather="file" class="align-text-bottom"></span><i class="bi bi-person-heart"></i>Profissionais'.html_safe, professionals_path, class: "nav-link link-mysidebar" %>
          </li>
          <li class="nav-item">
            <%= link_to '<span data-feather="file" class="align-text-bottom"></span><i class="bi bi-graph-up-arrow"></i>Relatórios'.html_safe, report_index_path, class: "nav-link link-mysidebar" %>
          </li>
          <li class="nav-item">
            <%= link_to '<span data-feather="file" class="align-text-bottom"></span><i class="bi bi-card-heading"></i>Manual'.html_safe, manual_manual_myclinic_path, class: "nav-link link-mysidebar" %>
          </li>
          <li class="nav-item">
            <p align="center" style="margin-top: 5px;">
              <%= image_tag "logo.png", size: "200x60" %>
            </p>
          </li>             
        </ul>  
      </div>
    </nav>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">